name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

      # ---- Build & Push (force lowercase repo path) ----
      - name: Compute image names (lowercase)
        id: img
        run: |
          REPO_LC="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=ghcr.io/${REPO_LC}/todo-api:${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "IMAGE_LATEST=ghcr.io/${REPO_LC}/todo-api:latest" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t "${{ steps.img.outputs.IMAGE }}" -f docker/Dockerfile .

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push "${{ steps.img.outputs.IMAGE }}"
          docker tag "${{ steps.img.outputs.IMAGE }}" "${{ steps.img.outputs.IMAGE_LATEST }}"
          docker push "${{ steps.img.outputs.IMAGE_LATEST }}"
