name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests
  env:
    PYTHONPATH: .
  run: pytest -q

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/todo-api:${{ github.sha }} -f docker/Dockerfile .

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/todo-api:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}/todo-api:${{ github.sha }} ghcr.io/${{ github.repository }}/todo-api:latest
          docker push ghcr.io/${{ github.repository }}/todo-api:latest
